FROM dunglas/frankenphp:1-php8.4-alpine

WORKDIR /app

# Outils nécessaires pour convertir les PDF en images
RUN apk add --no-cache \
    poppler-utils \
    imagemagick

RUN install-php-extensions \
    pdo_pgsql pcntl opcache zip redis intl xdebug

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./
# (s) veut dire ne rien copier si le dossier app-module n'existe pas (utile pour le premier setup)
COPY app-module[s] ./app-modules
RUN composer install --no-scripts --no-interaction

COPY . .

ENV SERVER_NAME=":8080"
ENV APP_ENV=local
EXPOSE 8080

ENTRYPOINT ["php", "artisan", "octane:frankenphp", "--host=0.0.0.0", "--port=8080", "--watch"]